import manifest from "./imagery-manifest.json";

/**
 * Static satellite imagery registry. Images are stitched Esri World Imagery
 * (the same source The Aerial uses) generated by scripts/fetch-imagery.mjs;
 * the manifest carries each image's exact geographic bounds so pins project
 * accurately. Attribution: Esri, Maxar, Earthstar Geographics, and the GIS
 * User Community.
 */

export type MapImageId = keyof typeof manifest;

export interface MapImage {
  id: string;
  src: string;
  width: number;
  height: number;
  bounds: { west: number; east: number; north: number; south: number };
}

export const mapImages = manifest as Record<MapImageId, MapImage>;

const mercY = (lat: number) =>
  Math.log(Math.tan(Math.PI / 4 + (lat * Math.PI) / 360));

/** Project lat/lon to pixel coordinates within a map image. */
export function projectToImage(
  img: MapImage,
  lat: number,
  lon: number
): { x: number; y: number; inside: boolean } {
  const { west, east, north, south } = img.bounds;
  const x = ((lon - west) / (east - west)) * img.width;
  const y =
    ((mercY(north) - mercY(lat)) / (mercY(north) - mercY(south))) * img.height;
  const inside = x >= 0 && x <= img.width && y >= 0 && y <= img.height;
  return { x, y, inside };
}

export interface GeoPin {
  label: string;
  lat: number;
  lon: number;
  major?: boolean;
  desktopOnly?: boolean;
  /** Place the label on this side of the dot (default: right). */
  side?: "left" | "right";
}

/** Verified coordinates for the places Raegan serves. */
export const coastPins: GeoPin[] = [
  { label: "Fernandina Beach", lat: 30.6697, lon: -81.4626 },
  { label: "Historic District", lat: 30.6685, lon: -81.4615, desktopOnly: true, side: "left" },
  { label: "Crane Island", lat: 30.6135, lon: -81.473, major: true, side: "left" },
  { label: "Amelia Island", lat: 30.58, lon: -81.444, major: true },
  { label: "Summer Beach", lat: 30.5942, lon: -81.4447, desktopOnly: true, side: "right" },
  { label: "Amelia Island Plantation", lat: 30.527, lon: -81.45, desktopOnly: true, side: "left" },
  { label: "Wildlight", lat: 30.6266, lon: -81.6408 },
  { label: "Yulee", lat: 30.633, lon: -81.5815, desktopOnly: true },
];

export function pinFor(label: string): GeoPin | undefined {
  return coastPins.find((p) => p.label === label);
}

/* ------------------------------------------------------------------ *
 * Live MapLibre geography — ported from The Aerial / Heymann Williams
 * coastal, trimmed to Nassau County. MapLibre uses [lon, lat] order.
 * ------------------------------------------------------------------ */

export interface MapView {
  center: [number, number]; // [lon, lat]
  zoom: number;
  pitch: number;
  bearing: number;
}

export const ISLAND_CENTER: [number, number] = [-81.4539, 30.6156];

/** Camera kept over Nassau County and its water, with room to bank. */
export const MAX_BOUNDS: [[number, number], [number, number]] = [
  [-82.2, 30.05],
  [-80.6, 31.1],
];

/** Resting frame: the island and its water, pitched. */
export const HOME_VIEW: MapView = {
  center: [-81.452, 30.605],
  zoom: 11.7,
  pitch: 60,
  bearing: -26,
};

/** Where the intro fly-in begins (out over the Atlantic, flat). */
export const APPROACH_VIEW: MapView = {
  center: [-81.05, 30.3],
  zoom: 7.4,
  pitch: 0,
  bearing: 22,
};

/** The hero's opening flight: APPROACH_VIEW → HERO_VIEW after the boot gate. */
export const HERO_APPROACH: MapView = APPROACH_VIEW;
export const HERO_VIEW: MapView = HOME_VIEW;

export const HOME_ZOOM_RANGE = { minZoom: 6.2, maxZoom: 17.8 };

/**
 * Hand-traced Amelia Island Atlantic shoreline ([lon, lat], north → south).
 * The agents page projects this through the live camera to clip the ocean
 * portrait along the beach.
 */
export const AMELIA_ATLANTIC_COASTLINE: [number, number][] = [
  [-81.4385, 30.7195],
  [-81.4364, 30.7115],
  [-81.4336, 30.7045],
  [-81.4299, 30.6958],
  [-81.4281, 30.6852],
  [-81.4294, 30.6751],
  [-81.4318, 30.6646],
  [-81.4334, 30.6532],
  [-81.4341, 30.6415],
  [-81.4339, 30.6285],
  [-81.4359, 30.6165],
  [-81.4395, 30.6042],
  [-81.4435, 30.5921],
  [-81.4466, 30.5792],
  [-81.4481, 30.566],
  [-81.4479, 30.553],
  [-81.4454, 30.5404],
  [-81.442, 30.5282],
  [-81.4387, 30.5154],
  [-81.436, 30.5038],
];

/** Past this zoom the photoreal 3D tiles take over; hysteresis prevents flicker. */
export const PHOTOREAL_ON = 15.2;
export const PHOTOREAL_OFF = 14.4;

export const REGIONS: { key: string; name: string; lat: number; lon: number; zoom: number }[] = [
  { key: "island", name: "Amelia Island", lat: 30.64, lon: -81.45, zoom: 11.6 },
  { key: "south", name: "Plantation & South End", lat: 30.545, lon: -81.45, zoom: 12.1 },
  { key: "yulee", name: "Yulee & Mainland", lat: 30.62, lon: -81.59, zoom: 11.2 },
];

export const LANDMARKS: { name: string; lat: number; lon: number }[] = [
  { name: "Cumberland Island", lat: 30.85, lon: -81.45 },
  { name: "Fort Clinch", lat: 30.7047, lon: -81.4545 },
  { name: "Amelia Island Light", lat: 30.6732, lon: -81.4425 },
  { name: "KFHB · Fernandina Airport", lat: 30.6119, lon: -81.4613 },
  { name: "Downtown Fernandina", lat: 30.6697, lon: -81.4637 },
  { name: "St. Marys Inlet", lat: 30.7073, lon: -81.4402 },
  { name: "Amelia River · ICW", lat: 30.645, lon: -81.485 },
  { name: "Main Beach", lat: 30.6642, lon: -81.4283 },
  { name: "Amelia Island Plantation", lat: 30.5298, lon: -81.4476 },
];

export const AIRPORTS: { name: string; lat: number; lon: number }[] = [
  { name: "Jacksonville International", lat: 30.4941, lon: -81.6879 },
  { name: "Fernandina Beach Municipal", lat: 30.6119, lon: -81.4613 },
];

export function landmark(name: string): { name: string; lat: number; lon: number } | undefined {
  return LANDMARKS.find((l) => l.name === name);
}

/** A close, slightly pitched frame on any point. */
export function closeView(
  lat: number,
  lon: number,
  zoom = 13.4,
  pitch = 52,
  bearing = -18
): MapView {
  return { center: [lon, lat], zoom, pitch, bearing };
}
